"""
Interactive plugin generator for Memoria.

Generates a local Memoria plugin module and optional supporting files.
The generated plugin is compatible with the existing MemoriaPluginManager
local-plugin discovery mechanism.
"""

from __future__ import annotations

import re
from pathlib import Path


HOOK_GROUPS = {
    "analysis": [
        ("memoria_analysis_pre", "records, context"),
        ("memoria_analysis_post", "metrics, summary"),
    ],
    "evaluation": [
        ("memoria_register_benchmark_adapter", ""),
        ("memoria_register_analyzer", ""),
    ],
    "feedback": [
        ("memoria_register_feedback_recorder", ""),
        ("memoria_feedback_pre", "query, result_id"),
        ("memoria_feedback_post", "query, result_id, success"),
    ],
    "ingestion": [
        ("memoria_register_extractor", ""),
        ("memoria_register_entity_recognizer", ""),
        ("memoria_ingestion_pre", "text, metadata"),
        ("memoria_ingestion_post", "record"),
    ],
    "lifecycle": [
        ("memoria_on_startup", ""),
        ("memoria_on_shutdown", ""),
        ("memoria_pre_query", "text"),
        ("memoria_post_query", "text, response"),
        ("memoria_pre_store", "text, metadata"),
        ("memoria_post_store", "mem_id, text, metadata"),
    ],
    "query": [
        ("memoria_register_query_processor", ""),
        ("memoria_query_process_pre", "text"),
        ("memoria_query_process_post", "query_record"),
    ],
    "ranking": [
        ("memoria_register_ranking_signal", ""),
        ("memoria_register_reranker", ""),
        ("memoria_ranking_pre", "query, candidates"),
        ("memoria_ranking_post", "query, candidates, scored_candidates"),
    ],
    "retrieval": [
        ("memoria_register_retriever", ""),
        ("memoria_retrieval_pre", "query, candidates"),
        ("memoria_retrieval_post", "query, candidates, results"),
    ],
    "routing": [
        ("memoria_register_type_router", ""),
        ("memoria_register_signal_router", ""),
        ("memoria_routing_pre", "query, memory_type_hint"),
        ("memoria_routing_post", "route"),
    ],
    "scheduler": [
        ("memoria_register_worker", ""),
        ("memoria_register_scheduler_policy", ""),
        ("memoria_scheduler_pre", "task_ids"),
        ("memoria_scheduler_post", "execution_result"),
    ],
    "storage": [
        ("memoria_register_database_backend", ""),
        ("memoria_register_vector_store", ""),
        ("memoria_storage_pre", "text, metadata"),
        ("memoria_storage_post", "mem_id, text, metadata"),
    ],
}


def normalize_plugin_name(name: str) -> str:
    """
    Convert a user-provided plugin name into a safe Python module name.

    Examples:
        "GitHub Tools" -> "github_tools"
        "github-tools" -> "github_tools"
        "MyPlugin" -> "myplugin"
    """
    value = name.strip().lower()
    value = re.sub(r"[^a-z0-9_]+", "_", value)
    value = re.sub(r"_+", "_", value)
    value = value.strip("_")

    if not value:
        raise ValueError("Plugin name must contain at least one letter or digit.")

    if value[0].isdigit():
        value = f"plugin_{value}"

    return value


def plugin_class_name(plugin_name: str) -> str:
    """Convert a normalized plugin name into a Python class name."""
    parts = [part for part in plugin_name.split("_") if part]

    if parts and parts[-1] == "plugin":
        return "".join(part.capitalize() for part in parts)

    return "".join(part.capitalize() for part in parts) + "Plugin"


def validate_hook_groups(hook_groups: list[str]) -> list[str]:
    """Validate and normalize selected hook groups."""
    normalized = []

    for group in hook_groups:
        group_name = group.strip().lower()

        if not group_name:
            continue

        if group_name not in HOOK_GROUPS:
            available = ", ".join(HOOK_GROUPS)
            raise ValueError(
                f"Unknown hook group '{group_name}'. "
                f"Available groups: {available}"
            )

        if group_name not in normalized:
            normalized.append(group_name)

    return normalized


def render_plugin_module(
    plugin_name: str,
    description: str,
    hook_groups: list[str],
) -> str:
    """Render the Python source for a generated plugin."""
    class_name = plugin_class_name(plugin_name)

    lines = [
        '"""',
        f"{description.strip() or f'{class_name} for Memoria.'}",
        "",
        "Generated by the Memoria plugin generator.",
        '"""',
        "",
        "from core.plugin_manager import hookimpl",
        "",
        "",
        f"class {class_name}:",
        f'    """Memoria plugin: {description.strip() or plugin_name}."""',
        "",
        f'    __plugin_name__ = "{plugin_name}"',
    ]

    if not hook_groups:
        lines.extend(
            [
                "",
                "    pass",
            ]
        )
    else:
        for group in hook_groups:
            lines.append("")
            lines.append(f"    # {group} hooks")

            for hook_name, signature in HOOK_GROUPS[group]:
                lines.extend(
                    [
                        "",
                        "    @hookimpl",
                        f"    def {hook_name}(self{', ' if signature else ''}{signature}):",
                        "        \"\"\"Generated hook implementation placeholder.\"\"\"",
                        "        return None",
                    ]
                )

    lines.extend(
        [
            "",
            "",
            f"plugin = {class_name}()",
            "",
        ]
    )

    return "\n".join(lines)


def render_readme(
    plugin_name: str,
    description: str,
    hook_groups: list[str],
) -> str:
    """Render Markdown documentation for a generated plugin."""
    title = plugin_name.replace("_", " ").title()

    lines = [
        f"# {title}",
        "",
        description.strip() or f"Memoria plugin: {plugin_name}.",
        "",
        "## Plugin",
        "",
        f"- Name: `{plugin_name}`",
        f"- Module: `{plugin_name}.py`",
        "",
        "## Hook Groups",
        "",
    ]

    if hook_groups:
        for group in hook_groups:
            lines.append(f"- `{group}`")
    else:
        lines.append("- None selected")

    lines.extend(
        [
            "",
            "## Installation",
            "",
            "Place the generated Python module in the Memoria plugin directory.",
            "The default local plugin directory is `plugins/`.",
            "",
            "The Memoria plugin manager discovers the module automatically when",
            "plugin auto-loading is enabled.",
            "",
            "## Development",
            "",
            "The generated hook implementations are placeholders.",
            "Replace the `return None` bodies with the behavior required by the hook.",
            "",
        ]
    )

    return "\n".join(lines)


def render_tests(
    plugin_name: str,
    hook_groups: list[str],
) -> str:
    """Render a basic test module for a generated plugin."""
    all_hooks = []

    for group in hook_groups:
        for hook_name, _signature in HOOK_GROUPS[group]:
            all_hooks.append(hook_name)

    lines = [
        '"""Tests for the generated Memoria plugin."""',
        "",
        "import importlib.util",
        "from pathlib import Path",
        "",
        "import pluggy",
        "",
        "",
        "PLUGIN_PATH = Path(__file__).resolve().parents[1]",
        f'PLUGIN_FILE = PLUGIN_PATH / "{plugin_name}.py"',
        "",
        "",
        "def load_plugin_module():",
        '    spec = importlib.util.spec_from_file_location("generated_plugin", PLUGIN_FILE)',
        "    if spec is None or spec.loader is None:",
        "        raise RuntimeError(f\"Unable to load plugin module: {PLUGIN_FILE}\")",
        "",
        "    module = importlib.util.module_from_spec(spec)",
        "    spec.loader.exec_module(module)",
        "    return module",
        "",
        "",
        "def test_plugin_module_loads():",
        "    module = load_plugin_module()",
        "    plugin = module.plugin",
        f'    if getattr(plugin, "__plugin_name__", None) != "{plugin_name}":',
        "        raise RuntimeError(\"Generated plugin has an unexpected plugin name\")",
        "",
        "",
        "def test_plugin_is_pluggy_compatible():",
        "    module = load_plugin_module()",
        "    plugin = module.plugin",
        "",
        '    pm = pluggy.PluginManager("memoria")',
        "    pm.register(plugin)",
        "",
        "    if not pm.is_registered(plugin):",
        "        raise RuntimeError(\"Generated plugin was not registered with Pluggy\")",
        "",
    ]

    if all_hooks:
        lines.extend(
            [
                "",
                "def test_generated_hooks_exist():",
                "    module = load_plugin_module()",
                "    plugin = module.plugin",
                "",
            ]
        )

        for hook_name in all_hooks:
            lines.extend(
                [
                    f'    if not callable(getattr(plugin, "{hook_name}", None)):',
                    f'        raise RuntimeError("Missing generated hook: {hook_name}")',
                ]
            )

        lines.append("")

    return "\n".join(lines)


def generate_plugin(
    plugin_name: str,
    description: str = "",
    hook_groups: list[str] | None = None,
    output_dir: str | Path = "plugins",
    create_tests: bool = True,
    create_readme: bool = True,
) -> dict[str, Path]:
    """
    Generate a Memoria plugin.

    Returns a mapping of generated file types to their paths.
    """
    normalized_name = normalize_plugin_name(plugin_name)
    selected_groups = validate_hook_groups(hook_groups or [])
    output_path = Path(output_dir)

    output_path.mkdir(parents=True, exist_ok=True)

    plugin_file = output_path / f"{normalized_name}.py"

    if plugin_file.exists():
        raise FileExistsError(
            f"Plugin already exists: {plugin_file}"
        )

    generated = {}

    plugin_file.write_text(
        render_plugin_module(
            normalized_name,
            description,
            selected_groups,
        ),
        encoding="utf-8",
    )
    generated["plugin"] = plugin_file

    if create_readme:
        readme_file = output_path / f"{normalized_name}.md"

        readme_file.write_text(
            render_readme(
                normalized_name,
                description,
                selected_groups,
            ),
            encoding="utf-8",
        )

        generated["readme"] = readme_file

    if create_tests:
        tests_dir = output_path / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        test_file = tests_dir / f"test_{normalized_name}.py"

        test_file.write_text(
            render_tests(
                normalized_name,
                selected_groups,
            ),
            encoding="utf-8",
        )

        generated["tests"] = test_file

    return generated
